services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run 
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ./cloudflared:/etc/cloudflared

  traefik:
    image: traefik:latest 
    container_name: traefik
    command:
      - --configFile=/traefik.yaml
    restart: unless-stopped
    networks:
      - proxy 
    volumes:
      - ./data/traefik.yaml:/traefik.yaml:ro 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - /etc/localtime:/etc/localtime:ro 
    env_file: .env 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.entrypoints=http"
      - "traefik.http.routers.web.rule=Host(`traefik-dashboard.notoriousdev.in`)"
      - "traefik.http.middlewares.web-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.routers.web.middlewares=web-auth"
      - "traefik.http.routers.web.service=api@internal"
networks:
  proxy:
    external: true
